[[plugins]]
package = "@netlify/plugin-gatsby"

[functions]
  included_files = ["!.cache/data/datastore/data.mdb","!.cache/query-engine/assets/vendor/8.12.2/linux-x64/lib/libvips-cpp.so.42","!.cache/query-engine/assets/vendor/8.11.3/linux-x64/lib/libvips-cpp.so.42",".cache/query-engine/assets/vendor1/8.11.3/linux-x64/lib/libvips-cpp.so.42"!]
