agentName: active-directory
agentType: integration
title: 'Active Directory monitoring integration'
metaDescription: 'Install the Active Directory integration'
introFilePath: 'src/install/active-directory/intro.mdx'

steps:
  - filePath: 'src/install/active-directory/install-infra.mdx'
  - filePath: "src/install/active-directory/install-integration.mdx"             
  - filePath: 'src/install/active-directory/configure-integration.mdx'
  - filePath: 'src/install/active-directory/install-io.mdx'
  - filePath: 'src/install/active-directory/find-data.mdx'
whatsNextFilePath: 'src/install/active-directory/whatsNext.mdx'
