agentName: aim
agentType: aimon
title: 'Install AI Monitoring'
metaDescription: 'Track the performance of your entire AI stack.'
introFilePath: 'src/install/aim/intro.mdx'
appInfo:
  - optionType: agent-lang
    label: "Choose your app's language"
    placeholder: 
    options:
      - value: 'nodejs'
        displayName: 'Node.js'
      - value: 'python'
        displayName: 'Python'

steps:
  - filePath: 'src/install/aim/appInfo.mdx'
  - filePath: 'src/install/aim/agent-lang/nodejs.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'nodejs'
  - filePath: 'src/install/aim/agent-lang/python.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'python'
whatsNextFilePath: 'src/install/aim/whatsNext.mdx'
