agentName: aim
agentType: aimon
title: 'Install AI Monitoring'
metaDescription: 'Track the performance of your entire AI stack.'
introFilePath: 'src/install/aim/intro.mdx'
appInfo:
  - optionType: agent-lang
    label: "Choose your app's language"
    placeholder: 'why tf does this say python kill me now'
    options:
      - value: 'nodejs'
        displayName: 'Node.js'
      - value: 'python'
        displayName: 'Python'

steps:
  - filePath: 'src/install/aim/appInfo.mdx'
  - filePath: 'src/install/aim/default.mdx' 
    overrides:
      - filePath: 'src/install/aim/agent-lang/nodejs-install.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'nodejs'
      - filePath: 'src/install/aim/agent-lang/python-install.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'python'   
  - filePath: 'src/install/aim/agentConfigDefault.mdx'
    overrides:
      - filePath: 'src/install/aim/agent-lang/node-config.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'nodejs'
      - filePath: 'src/install/aim/agent-lang/python-config.mdx'
        selectedOptions:
          - optionType: agent-lang
            options:
              - value: 'python'  
  - filePath: 'src/install/aim/view-your-data.mdx'
whatsNextFilePath: 'src/install/aim/whatsNext.mdx'
