agentName: apache
agentType: integration
title: 'Apache monitoring integration'
metaDescription: 'Install the Apache integration'
introFilePath: 'src/install/apache/intro.mdx'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration
  - /docs/infrastructure/integrations/integrations/apache-integration-new-relic-infrastructure
  - /docs/apache-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration


# -----------------------------------------------------------------
# Create the buttons for the question you want to ask:
# -----------------------------------------------------------------
appInfo: 
  - optionType: deployment
    label: ""
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'
        recommendedGuided: true        
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true        
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
        recommendedGuided: true        
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
        recommendedGuided: true        
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"  
        recommendedGuided: true        
        logo: 'linux'                  

# ----------------------------------------------------
# Ask the first question and then provide instructions
# ----------------------------------------------------
steps:
  # Step 1: Ask the user what kind of deployment--not their OS
  - filePath: 'src/install/apache/appInfo.mdx'

  # Step 2: Display the requirements
  - filePath: 'src/install/apache/default-requirements.mdx'

  # Step 3: Display the instructions to install the infra agent (prerequisite)
  - filePath: 'src/install/apache/install-infra.mdx'

  # Step 4: Display the Apache integration download and installation instructions 
  # based on their answer in question 1 above. Note the overrides:
  - filePath: "src/install/apache/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/apache/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/apache/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/apache/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/apache/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/apache/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"  

  # Step 5: Display the configuration options               
  - filePath: 'src/install/apache/default-configuration-linux.mdx'
    overrides: 
        - filePath: 'src/install/apache/windows/configure-windows.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'msi' 

  # Step 6: View your data    
  - filePath: 'src/install/apache/find-data.mdx'

# Display a reference list of configurations and show some examples
whatsNextFilePath: 'src/install/apache/whatsNext.mdx'
