agentName: apache
agentType: integration
title: 'Apache monitoring integration'
metaDescription: 'Install the Apache integration'
introFilePath: 'src/install/apache/intro.mdx'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/apache-monitoring-integration
  - /docs/infrastructure/integrations/integrations/apache-integration-new-relic-infrastructure
  - /docs/apache-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/apache-monitoring-integration


# -----------------------------------------------------------------
# Define the categories for each type of question you'll be asking:
# -----------------------------------------------------------------
appInfo: 
  - optionType: guided-install
    label: 'How much help do you need?'
    placeholder: 'Choose one:'
    options:
      - value: 'guided-install-yes'
        displayName: 'Let the guided install do the work'
      - value: 'manual-install-yes'
        displayName: 'I prefer to install manually'

  - optionType: deployment
    label: 'Choose your install path'
    placeholder: 'Choose one:'
    options:
      - value: 'msi'
        displayName: 'Install using MSI files (Windows)'
        logo: 'windows'
        recommendedGuided: true        
      - value: 'apt'
        displayName: 'Install using Apt (Debian, Ubuntu)'
        recommendedGuided: true        
      - value: 'yum'
        logo: 'linux'      
        displayName: 'Install using Yum (Amazon Linux, CentOS, RHEL)'
        recommendedGuided: true        
      - value: 'zypper'
        displayName: 'Install using Zypper (SLES)'
        recommendedGuided: true        
        logo: 'linux'        
      - value: 'tar'
        displayName: 'Install from tarball (Other Linux distros)'  
        recommendedGuided: true        
        logo: 'linux'                  

# ----------------------------------------------------
# Ask the user some questions
# ----------------------------------------------------
steps:
  # Step 1: Ask the user if they want to use the guided install:
  - filePath: 'src/install/apache/want-guided-install.mdx'

  # Step 2: Ask the user what kind of deployment--not their OS
  - filePath: 'src/install/apache/appInfo.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: guided-install
            options:
              - value: 'guided-install-yes'

# ----------------------------------------------------
# Display the instructions based on their answer:
# ----------------------------------------------------
  
  # Step 3: Display the requirements
  - filePath: 'src/install/apache/default-requirements.mdx'
  
  # Step 4: Display the instructions to install the infra agent (prereq)
  - filePath: 'src/install/apache/install-infra.mdx'

  # Step 5: Display the Apache integration download and installation instructions 
  # based on their answer in question 1 above. Note the overrides:
  - filePath: 'src/install/apache/linux/install-apt.mdx'
    overrides: 
      - isConditionalStep: true
      - filePath: 'src/install/apache/linux/install-apt.mdx'           
        selectedOptions: 
          - optionType: deployment
            options: 
              - value: 'apt'
          # Apply AND logic
          - optionType: manual-install
            options:
              - value: 'manual-install-yes'
      - filePath: 'src/install/apache/linux/install-tarball.mdx'
        selectedOptions: 
          - optionType: deployment
            options: 
              - value: 'tar'
          # Apply AND logic
          - optionType: manual-install
            options:
              - value: 'manual-install-yes'
      - filePath: 'src/install/apache/linux/install-yum.mdx'
        selectedOptions: 
          - optionType: deployment
            options: 
              - value: 'yum'
          # Apply AND logic
          - optionType: manual-install
            options:
              - value: 'manual-install-yes'
      - filePath: 'src/install/apache/linux/install-zypper.mdx'
        selectedOptions: 
          - optionType: deployment
            options: 
              - value: 'zypper'
          # Apply AND logic
          - optionType: manual-install
            options:
              - value: 'manual-install-yes'
      - filePath: 'src/install/apache/windows/install-msi.mdx'
        selectedOptions: 
          - optionType: deployment
            options: 
              - value: 'msi' 
          # Apply AND logic
          - optionType: manual-install
            options:
              - value: 'manual-install-yes'  

  # Step 6: Display the configuration options               
  - filePath: 'src/install/apache/default-configure-linux.mdx'
    overrides: 
        - filePath: 'src/install/apache/windows/configure-windows.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'msi' 

  # Step 7: Find your data        
  - filePath: 'src/install/apache/find-data.mdx'

whatsNextFilePath: 'src/install/apache/whatsNext.mdx'
