agentName: aws-cloudwatch
agentType: integration
title: 'Amazon CloudWatch Metric Streams'
metaDescription: 'Install the Amazon CloudWatch Metric Streams integration'
introFilePath: 'src/install/aws-cloudwatch/intro.mdx'
redirects:
  - /docs/infrastructure/amazon-integrations/get-started/aws-metric-stream-setup
appInfo: 
  - optionType: task
    label: ''
    placeholder: 'Choose how to set up'
    options: 
      - value: 'cloudformation'
        displayName: 'Create a Cloudformation template'
        logo: 'cloudformation'
      - value: 'console'
        displayName: 'Use AWS console'
        logo: 'console'
      - value: 'migrate'
        displayName: 'Migrate from API polling'
        logo: 'cloudwatch'

steps:
  - filePath: 'src/install/aws-cloudwatch/appInfo.mdx'
  - filePath: 'src/install/aws-cloudwatch/permissions.mdx'
  - filePath: 'src/install/aws-cloudwatch/default.mdx'
    overrides: 
        - filePath: 'src/install/aws-cloudwatch/cloudwatch-path/cloudformation.mdx'
          selectedOptions: 
            - optionType: task
              options: 
                - value: 'cloudformation'
        - filePath: 'src/install/aws-cloudwatch/cloudwatch-path/console.mdx'
          selectedOptions: 
            - optionType: task
              options: 
                - value: 'console'
        - filePath: 'src/install/aws-cloudwatch/cloudwatch-path/migrate.mdx'
          selectedOptions: 
            - optionType: task
              options: 
                - value: 'migrate'
  - filePath: 'src/install/aws-cloudwatch/validate-data.mdx'
whatsNextFilePath: 'src/install/aws-cloudwatch/whatsNext.mdx'
