agentName: aws-logs
agentType: integration
title: 'Forward AWS logs'
metaDescription: 'Forward logs from AWS'
introFilePath: 'src/install/aws-logs/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'firehouse'
        displayName: 'Amazon Kinesis Firehouse'
      - value: 'firelens'
        displayName: 'AWS FireLens'
      - value: 's3'
        displayName: 'AWS S3'        
      - value: 'cloudwatch'
        displayName: 'AWS Cloudwatch'
      - value: 'security-lake'
        displayName: "AWS Security Lake"         

steps:
  - filePath: 'src/install/aws-logs/appInfo.mdx'
    overrides: 
        - filePath: "src/install/aws-logs/firehouse"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/aws-logs/firelens"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/aws-logs/s3"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/aws-logs/cloudwatch"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/aws-logs/security-lake"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"  
  - filePath: 'src/install/aws-logs/host/percona.mdx'
    overrides:  
        - filePath: 'src/install/aws-logs/host/percona.mdx'
          selectedOptions:
            - optionType: hosted
              options:
                - value: 'percona'
        - filePath: 'src/install/aws-logs/host/atlas.mdx'
          selectedOptions:
            - optionType: hosted
              options:
                - value: 'atlas'                  
  - filePath: 'src/install/aws-logs/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/aws-logs/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/aws-logs/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'         
  - filePath: 'src/install/aws-logs/find-data.mdx'
whatsNextFilePath: 'src/install/aws-logs/whatsNext.mdx'
