agentName: aws_logs
agentType: integration
title: 'Forward AWS logs'
metaDescription: 'Forward logs from AWS'
introFilePath: 'src/install/aws_logs/intro.mdx'
appInfo: 
  - optionType: service
    label: 'What type of AWS service are you forwarding logs from?'
    placeholder: 'Choose one:'
    options: 
      - value: 'EC2'
        displayName: 'Amazon EC2'
      - value: 'EKS'
        displayName: 'Amazon EKS'
      - value: 'ECS'
        displayName: 'Amazon ECS'        
      - value: 'security_lake'
        displayName: 'Amazon route 53 logs / VPC Flow logs / AWS Cloudtrail logs/ AWS Security Hub'   
      - value: 'other'
        displayName: 'Other log types'            
  - optionType: forward_EC2
    label: 'How would you like to forward your EC2 logs?'
    placeholder: 'Choose one:'
    options: 
      - value: 'infra_fluentbit'
        displayName: 'Infrastructure agent with Fluentbit'
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function'
      - value: 'data_firehose'
        displayName: 'Kinesis Data Firehose'        
  - optionType: forward_EKS
    label: 'How would you like to forward your EKS logs?'
    placeholder: 'Choose one:'
    options: 
      - value: 'k8s_integration'
        displayName: 'Kubernetes integration'
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function'
  - optionType: forward_ECS
    label: 'How would you like to forward your ECS logs?'
    placeholder: 'Choose one:'
    options: 
      - value: 'infra_fluentbit'
        displayName: 'Infrastructure agent with Fluentbit'
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function' 
      - value: 'sidecar_firelens'                          
        displayName: 'Sidecar container with Firelens'
  - optionType: forward_Other
    label: 'Select logs destination'
    placeholder: 'Choose one:'
    options: 
      - value: 'data_firehose'
        displayName: 'Kinesis Data Firehose'  
      - value: 'cloud_lambda'
        displayName: 'Cloudwatch Lambda Function'       
steps:
  - filePath: 'src/install/aws_logs/appInfo_service.mdx'
  - filePath: 'src/install/aws_logs/appInfo_EC2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'EC2'
  - filePath: 'src/install/aws_logs/appInfo_EKS.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'EKS' 
  - filePath: 'src/install/aws_logs/appInfo_ECS.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'ECS'       
  - filePath: 'src/install/aws_logs/appInfo_Other.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'other'               
  - filePath: 'src/install/aws_logs/security_lake/intro_securitylake.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'security_lake'         
  - filePath: 'src/install/aws_logs/agent/basic-agent.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'infra_fluentbit'     
  - filePath: 'src/install/aws_logs/cloudwatch/basic-cloudwatch.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'cloud_lambda' 
  - filePath: 'src/install/aws_logs/cloudwatch/cloudwatch-lambda.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'cloud_lambda' 
  - filePath: 'src/install/aws_logs/cloudwatch/configure-retries.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'cloud_lambda' 
  - filePath: 'src/install/aws_logs/cloudwatch/view-log-data.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'cloud_lambda'                                               
  - filePath: 'src/install/aws_logs/firehose/basic-firehose.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'data_firehose'   
  - filePath: 'src/install/aws_logs/firehose/firehose-buffer.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'data_firehose' 
  - filePath: 'src/install/aws_logs/firehose/firehose-eu.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'data_firehose'                  
  - filePath: 'src/install/aws_logs/firehose/firehose-view.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'data_firehose'                                            
  - filePath: 'src/install/aws_logs/k8s/basic-k8s.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'k8s_integration'        
  - filePath: 'src/install/aws_logs/firelens/basic-firelens.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'sidecar_firelens'                      
whatsNextFilePath: 'src/install/aws_logs/whatsNext.mdx'              