agentName: awsLogs
agentType: integration
title: 'Forward AWS logs'
metaDescription: 'Forward logs from AWS'
introFilePath: 'src/install/awsLogs/intro.mdx'
appInfo: 
  - optionType: service
    label: 'What type of AWS service are you forwarding logs from?'
    placeholder: 'Choose one:'
    options: 
      - value: 'EC2'
        displayName: 'Amazon EC2'
      - value: 'EKS'
        displayName: 'Amazon EKS'
      - value: 'ECS'
        displayName: 'Amazon ECS'        
      - value: 'cloudfront'
        displayName: 'Amazon Cloudfront'
      - value: 'security-lake'
        displayName: 'Amazon Security Lake'    
  - optionType: forward-EC2
    label: 'How would you like to forward your EC2 logs?'
    placeholder: 'Choose one:'
    options: 
      - value: 'infra-fluentbit'
        displayName: 'Infrastructure agent with Fluentbit'
      - value: 'cloud-lambda'
        displayName: 'Cloudwatch Lambda Function'
  - optionType: forward-EKS
    label: 'How would you like to forward your EKS logs?'
    placeholder: 'Choose one:'
    options: 
      - value: 'k8s-integration'
        displayName: 'Kubernetes integration'
      - value: 'cloud-lambda'
        displayName: 'Cloudwatch Lambda Function'
  - optionType: forward-ECS
    label: 'How would you like to forward your ECS logs?'
    placeholder: 'Choose one:'
    options: 
      - value: 'infra-fluentbit'
        displayName: 'Infrastructure agent with Fluentbit'
      - value: 'cloud-lambda'
        displayName: 'Cloudwatch Lambda Function' 
      - value: 'sidecar-firelens'                          
        displayName: 'Sidecar container with Firelens'
steps:
  - filePath: 'src/install/awsLogs/appInfo-service.mdx'
  - filePath: 'src/install/awsLogs/appInfo-EC2.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'EC2'
  - filePath: 'src/install/awsLogs/appInfo-EKS.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'EKS' 
  - filePath: 'src/install/awsLogs/appInfo-ECS.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'ECS'    
  - filePath: 'src/install/awsLogs/cloudfront/intro-cloudfront.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'cloudfront'    
  - filePath: 'src/install/awsLogs/security-lake/intro-securitylake.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: service
            options:
              - value: 'security-lake'                  