agentName: cassandra
agentType: integration
title: 'Cassandra monitoring integration'
metaDescription: 'Install the Cassandra integration'
introFilePath: 'src/install/cassandra/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'ecs'
        displayName: 'ECS'
        logo: 'amazonECS'
      - value: 'kubernetes'
        displayName: 'Kubernetes'
        logo: 'k8'
steps:
  - filePath: 'src/install/cassandra/guided.mdx'
  - filePath: 'src/install/cassandra/default-requirements.mdx'
    overrides: 
        - filePath: 'src/install/cassandra/ecs/requirements-ecs.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
        - filePath: 'src/install/cassandra/kubernetes/requirements-k8s.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'kubernetes'
        - filePath: 'src/install/cassandra/linux/requirements-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux' 
  - filePath: 'src/install/cassandra/install-infra.mdx'    
  - filePath: 'src/install/cassandra/default-install.mdx'
    overrides: 
        - filePath: 'src/install/cassandra/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/cassandra/ecs/install-ecs.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
        - filePath: 'src/install/cassandra/kubernetes/install-k8s.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'kubernetes'  
  - filePath: 'src/install/cassandra/update.mdx'
  - filePath: 'src/install/cassandra/find-data.mdx'
whatsNextFilePath: 'src/install/cassandra/whatsNext.mdx'