agentName: jmx
agentType: integration
title: 'JMX monitoring integration'
metaDescription: 'Install the JMX integration'
introFilePath: 'src/install/jmx/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'     
      - value: 'ecs'
        displayName: 'ECS'
        logo: 'amazonECS'
      - value: 'kubernetes'
        displayName: 'Kubernetes'
        logo: 'k8'

steps:
  - filePath: 'src/install/jmx/guided.mdx'
  - filePath: 'src/install/jmx/default-requirements.mdx'
    overrides: 
        - filePath: 'src/install/jmx/ecs/requirements-ecs.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
        - filePath: 'src/install/jmx/kubernetes/requirements-k8s.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'kubernetes'
  - filePath: 'src/install/jmx/install-infra.mdx'
  - filePath: 'src/install/jmx/linux/install-linux.mdx'
    overrides: 
        - filePath: 'src/install/jmx/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/jmx/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'           
        - filePath: 'src/install/jmx/ecs/install-ecs.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'ecs'
        - filePath: 'src/install/jmx/kubernetes/install-k8s.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'kubernetes'  
  - filePath: 'src/install/jmx/find-data.mdx'
whatsNextFilePath: 'src/install/jmx/whatsNext.mdx'