agentName: kafka
agentType: integration
title: "Kafka monitoring integration"
metaDescription: "Install the Kafka integration"
introFilePath: "src/install/kafka/intro.mdx"
appInfo: 
  - optionType: dropdown1
    label: "Select your deployment environment"
    placeholder: "Select your environment"
    options: 
      - value: "linux"
        displayName: "Linux"
        logo: "linux"
        recommendedGuided: true
      - value: "windows"
        displayName: "Windows"
        logo: "windows"
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
      - value: "yum"
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"
steps:
  - filePath: "src/install/kafka/appInfo.mdx"
  - filePath: "src/install/kafka/default-requirements.mdx"
  - filePath: "src/install/kafka/install-infra.mdx"
  - filePath: "src/install/kafka/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/kafka/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/kafka/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/kafka/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/kafka/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/kafka/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"                                                                
  - filePath: "src/install/kafka/default-install-linux.mdx"
    overrides: 
        - filePath: "src/install/kafka/linux/install-linux.mdx"
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: "linux"
        - filePath: "src/install/kafka/windows/install-windows.mdx"
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: "windows"
  - filePath: "src/install/kafka/default-configuration.mdx"
  - filePath: "src/install/kafka/find-data.mdx"
whatsNextFilePath: "src/install/kafka/whatsNext.mdx"
