agentName: kafka
agentType: integration
title: 'Kafka monitoring integration'
metaDescription: 'Here are several ways to install the Kafka integration'
introFilePath: 'src/install/kafka/intro.mdx'
redirects:
  - /docs/integrations/host-integrations/host-integrations-list/kafka-monitoring-integration
  - /docs/kafka-integration-new-relic-infrastructure
  - /docs/infrastructure/host-integrations/host-integrations-list/kafka-monitoring-integration
  - /docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-config
  - /docs/infrastructure/host-integrations/host-integrations-list/kafka/kafka-integration

appInfo:
  - optionType: deployment 
    label: ''
    placeholder: "Choose the option that best matches how you'll install the integration."
    options:
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
      - value: 'ecs'
        displayName: 'ECS'
        logo: 'amazonECS'
      - value: 'kubernetes'
        displayName: 'Kubernetes'
        logo: 'k8'  

  - optionType: linux
    label: ''
    placeholder: "How would you like to enable your Linux environment?"
    options:
      - value: 'apt'
        displayName: 'Install using Apt (Debian, Ubuntu)'
      - value: 'yum'
        displayName: 'Install using Yum (Amazon Linux, CentOS, RHEL)'
      - value: 'zypper'
        displayName: 'Install using Zypper (SLES)'     
      - value: 'tar'
        displayName: 'Install from Tarball (Other Linux distros)'        

  - optionType: windows
    label: ''
    placeholder: "How would you like to enable your Windows environment?"
    options:
      - value: 'msi'
        displayName: 'Install using MSI files'


steps:
  - filePath: 'src/install/kafka/appInfo.mdx'
  - filePath: 'src/install/kafka/linux-yes.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'linux'  
  - filePath: 'src/install/kafka/windows-yes.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'windows' 
  - filePath: 'src/install/kafka/ecs/install-ecs.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'ecs'
  - filePath: 'src/install/kafka/kubernetes/install-k8s.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'kubernetes'                

  - filePath: 'src/install/kafka/linux/install-apt.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'apt'

  - filePath: 'src/install/kafka/linux/install-yum.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'yum'

  - filePath: 'src/install/kafka/linux/install-zypper.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'zypper'

  - filePath: 'src/install/kafka/linux/install-tarball.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'tar'

  - filePath: 'src/install/kafka/windows/install-msi.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: windows
            options:
              - value: 'msi'

  - filePath: 'src/install/kafka/install-infra.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'ecs'
              - value: 'kubernetes'
      - isConditionalStep: true
        selectedOptions:              
          - optionType: linux
            options:
              - value: 'apt'
              - value: 'yum'
              - value: 'zypper'
              - value: 'tar'
      - isConditionalStep: true
        selectedOptions:              
          - optionType: windows
            options:
              - value: 'msi'

  - filePath: 'src/install/kafka/linux/install-linux.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: linux
            options:
              - value: 'apt'
              - value: 'yum'
              - value: 'zypper'
              - value: 'tar'

  - filePath: 'src/install/kafka/windows/configure-windows.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: windows
            options:
              - value: 'msi'


  # Tell users how to view their data:
  - filePath: 'src/install/kafka/find-data.mdx'
    overrides:
      - isConditionalStep: true
        selectedOptions:
          - optionType: deployment
            options:
              - value: 'kubernetes'
              - value: 'ecs'           
      - isConditionalStep: true
        selectedOptions:              
          - optionType: linux
            options:
              - value: 'apt'
              - value: 'yum'
              - value: 'zypper'
              - value: 'tar'
      - isConditionalStep: true
        selectedOptions:              
          - optionType: windows
            options:             
              - value: 'msi'

whatsNextFilePath: 'src/install/kafka/whatsNext.mdx'
