agentName: kubernetes
agentType: integration
title: 'Kubernetes monitoring integration'
metaDescription: 'Install the Kubernetes integration'
introFilePath: 'src/install/kubernetes/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your installation'
    options: 
      - value: 'guided'
        displayName: 'Guided install'
      - value: 'eks'
        displayName: 'EKS Fargate'
        logo: 'eks'
        recommendedGuided: true
      - value: 'gke'
        displayName: 'GKE Autopilot'
        logo: 'gke'
        recommendedGuided: true
      - value: 'helm'
        displayName: 'Helm'
        logo: 'helm'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
        recommendedGuided: true
steps:
  - filePath: 'src/install/kubernetes/guided.mdx'
  - filePath: 'src/install/kubernetes/default-requirements.mdx'
    overrides: 
        - filePath: 'src/install/kubernetes/guided/requirements-guided.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'guided'
        - filePath: 'src/install/kubernetes/helm/requirements-helm.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'helm'
        - filePath: 'src/install/kubernetes/windows/requirements-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'
  - filePath: 'src/install/kubernetes/install.mdx'
    overrides: 
        - filePath: 'src/install/kubernetes/guided/install-guided.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'guided' 
        - filePath: 'src/install/kubernetes/eks/install-eks.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'eks' 
        - filePath: 'src/install/kubernetes/gke/install-gke.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'gke' 
        - filePath: 'src/install/kubernetes/helm/install-helm.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'helm' 
        - filePath: 'src/install/kubernetes/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows' 
  - filePath: 'src/install/kubernetes/configuration.mdx'
    overrides: 
        - filePath: 'src/install/kubernetes/guided/configuration-guided.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'guided' 
        - filePath: 'src/install/kubernetes/eks/configuration-eks.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'eks' 
        - filePath: 'src/install/kubernetes/gke/configuration-gke.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'gke' 
        - filePath: 'src/install/kubernetes/helm/configuration-helm.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'helm' 
        - filePath: 'src/install/kubernetes/windows/configuration-windows.mdx'
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: 'windows' 
  - filePath: 'src/install/kubernetes/find-data.mdx'                
