agentName: ORACLE
agentType: integration
title: 'Oracle monitoring integration'
metaDescription: 'Install the Oracle integration'
introFilePath: 'src/install/oracle/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'      
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"      
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"  
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"     
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"       
        logo: 'linux'                  


steps:
  - filePath: 'src/install/oracle/appInfo.mdx'
  - filePath: 'src/install/oracle/prepare.mdx'  
  - filePath: 'src/install/oracle/install-infra.mdx'
  - filePath: "src/install/oracle/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/oracle/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/oracle/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/oracle/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/oracle/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/oracle/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"                   
  - filePath: 'src/install/oracle/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/oracle/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/oracle/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'  
  - filePath: 'src/install/oracle/users.mdx'                       
  - filePath: 'src/install/oracle/find-data.mdx'
whatsNextFilePath: 'src/install/oracle/whatsNext.mdx'
