agentName: perfmon
agentType: integration
title: 'PerfMon monitoring integration'
metaDescription: 'Install the PerfMon integration'
introFilePath: 'src/install/perfmon/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Choose your install method'
    options: 
      - value: 'installer'
        displayName: 'Installer'
      - value: 'manual'
        displayName: 'Manual'    
        

steps:
  - filePath: 'src/install/perfmon/install-infra.mdx'
  - filePath: 'src/install/perfmon/installer.mdx'
    overrides: 
        - filePath: 'src/install/perfmon/installer.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'installer'
        - filePath: 'src/install/perfmon/manual.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'manual'     
  - filePath: 'src/install/perfmon/find-data.mdx'
whatsNextFilePath: 'src/install/perfmon/whatsNext.mdx'