agentName: postgre-sql
agentType: integration
title: 'PostgreSQL monitoring integration'
metaDescription: 'Install the PostgreSQL integration'
introFilePath: 'src/install/postgre-sql/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
        recommendedGuided: true
      - value: 'k8'
        displayName: 'Kubernetes'
        logo: 'k8'
      - value: 'ecs'
        displayName: 'Amazon ECS'
        logo: 'amazonECS'
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:      
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true                
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"  
        recommendedGuided: true        
        logo: 'linux'        

steps:
  - filePath: 'src/install/postgre-sql/appInfo.mdx'
  - filePath: 'src/install/postgre-sql/default-requirements.mdx'
    overrides:
      - filePath: 'src/install/postgre-sql/requirements-k8.mdx'
        selectedOptions: 
          - optionType: dropdown1
            options: 
              - value: 'k8'
      - filePath: 'src/install/postgre-sql/requirements-amazonECS.mdx'
        selectedOptions: 
          - optionType: dropdown1
            options: 
              - value: 'ecs'
  - filePath: 'src/install/postgre-sql/install-infra.mdx'
  - filePath: "src/install/postgre-sql/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/postgre-sql/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/postgre-sql/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"          
  - filePath: 'src/install/postgre-sql/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/postgre-sql/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/postgre-sql/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'         
  - filePath: 'src/install/postgre-sql/find-data.mdx'
whatsNextFilePath: 'src/install/postgre-sql/whatsNext.mdx'

