agentName: redis
agentType: integration
title: 'redis monitoring integration'
metaDescription: 'Install the redis integration'
introFilePath: 'src/install/redis/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'linux'
        displayName: 'Linux'
        logo: 'linux'
        recommendedGuided: true
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'
        recommendedGuided: true
  - optionType: deployment
    label: "Choose your install path"
    placeholder: "Choose one:"
    options:
      - value: "msi"
        displayName: "Install using MSI files (Windows)"
        logo: 'windows'
        recommendedGuided: true        
      - value: "apt"
        displayName: "Install using Apt (Debian, Ubuntu)"
        recommendedGuided: true        
      - value: "yum"
        logo: 'linux'      
        displayName: "Install using Yum (Amazon Linux, CentOS, RHEL)"
        recommendedGuided: true        
      - value: "zypper"
        displayName: "Install using Zypper (SLES)"
        recommendedGuided: true        
        logo: 'linux'        
      - value: "tar"
        displayName: "Install from tarball (Other Linux distros)"  
        recommendedGuided: true        
        logo: 'linux'        
  - optionType: hosted
    label: "How is your database hosted"      
    placeholder: 'Choose one:'
    options:  
      - value: 'percona'
        displayName: 'Hosted redis or Percona servers'
        recommendedGuided: true             
      - value: 'atlas'
        displayName: 'Atlas'
        recommendedGuided: true             


steps:
  - filePath: 'src/install/redis/appInfo.mdx'
  - filePath: 'src/install/redis/default-requirements.mdx'
  - filePath: 'src/install/redis/install-infra.mdx'
  - filePath: "src/install/redis/linux/install-apt.mdx"
    overrides: 
        - filePath: "src/install/redis/linux/install-apt.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "apt"
        - filePath: "src/install/redis/linux/install-tarball.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "tar"
        - filePath: "src/install/redis/linux/install-yum.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "yum"
        - filePath: "src/install/redis/linux/install-zypper.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "zypper"
        - filePath: "src/install/redis/windows/install-msi.mdx"
          selectedOptions: 
            - optionType: deployment
              options: 
                - value: "msi"  
  - filePath: 'src/install/redis/host/percona.mdx'
    overrides:  
        - filePath: 'src/install/redis/host/percona.mdx'
          selectedOptions:
            - optionType: hosted
              options:
                - value: 'percona'
        - filePath: 'src/install/redis/host/atlas.mdx'
          selectedOptions:
            - optionType: hosted
              options:
                - value: 'atlas'                  
  - filePath: 'src/install/redis/default-install-linux.mdx'
    overrides: 
        - filePath: 'src/install/redis/linux/install-linux.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'linux'
        - filePath: 'src/install/redis/windows/install-windows.mdx'
          selectedOptions: 
            - optionType: dropdown1
              options: 
                - value: 'windows'         
  - filePath: 'src/install/redis/find-data.mdx'
whatsNextFilePath: 'src/install/redis/whatsNext.mdx'
