agentName: windows-service
agentType: integration
title: 'Windows service monitoring integration'
metaDescription: 'Install the Windows service integration'
introFilePath: 'src/install/windows-service/intro.mdx'
appInfo: 
  - optionType: dropdown1
    label: ''
    placeholder: 'Select your environment'
    options: 
      - value: 'windows'
        displayName: 'Windows'
        logo: 'windows'

steps:
  - filePath: 'src/install/windows-service/install-infra.mdx'
  - filePath: 'src/install/windows-service/install-integration.mdx'
  - filePath: 'src/install/windows-service/configure-integration.mdx'   
whatsNextFilePath: 'src/install/windows-service/whatsNext.mdx'
