name: Vale linter

on:
  pull_request:
    branches:
      - develop
      - tabatha/fix-vale-checks
  workflow_dispatch:

jobs:
  vale-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run vale
        uses: errata-ai/vale-action@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: __onlyModified
          onlyAnnotateModifiedLines: true
          debug: true
