name: Vale linter

on:
  pull_request:
    branches:
      - develop
      - clark/test-vale-comment

jobs:
  vale-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run vale
        uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          reporter: github-check
          fail_on_error: true
          filter_mode: added
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Comment on Failure
        if: failure()
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hello world ! :wave:
